AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Function for ec2 snapshots

Resources:
    defaultlambdafunc:
        Type: AWS::Serverless::Function

        Properties:
            Handler: lambda_function.lambda_handler
            Runtime: python3.12
            CodeUri: .
            Timeout: 30
            Policies:
                - AWSLambdaBasicExecutionRole
                - Statement:
                    - Effect: Allow
                      Action:
                            - ec2:CreateSnapshot
                            - ec2:DescribeVolumes
                            - ec2:CreateTags
                      Resource: "*"
            Events:
              DailyScheduleCreation:
                Type: Schedule
                Properties:
                  Schedule: rate(1 day)

